theme: jekyll-theme-minimal
logo: LabLogo2_B.png
title: Michael Mangan's webpage
description: Personal page of Dr. Michael Mangan2, Dept. of Computer Science, University of Sheffield, UK
show_downloads: true
google_analytics:






