theme: jekyll-theme-minimal
logo: MMangan1 (1).jpg
title: Dr. Mike Mangan
description: Personal page of Dr. Michael Mangan, Dept. of Computer Science, University of Sheffield, UK
show_downloads: true
google_analytics:






