theme: jekyll-theme-minimal
logo: 
title: Michael Mangan's webpage
description: Personal page of Dr. Michael Mangan, Dept. of Computer Science, University of Sheffield, UK
show_downloads: true
google_analytics:






