theme: jekyll-theme-minimal
title: [Michael Mangan's webpage]
description: [Personal page of Dr. Michael Mangan, [Dept. of Computer Science](https://www.sheffield.ac.uk/dcs) at the [University of Sheffield, UK](https://www.sheffield.ac.uk/).
logo: [/MMangan1 (1).jpg]
