theme: jekyll-theme-minimal
logo: MMangan1 (1).jpg
title: Dr. Mike Mangan
description: Lecturer in Machine Learning and Robotics, Dept. of Computer Science, University of Sheffield, UK
show_downloads: true
google_analytics:






